version: "3.7"

services:
  app:
    build: ./
    volumes:
      - ./src/:/var/app/src
      - ./resources/:/var/app/resources
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    image: mariadb:10.4
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./database/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: "mysqld --init-file /data/application/init.sql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
